{{- $namespace := .Release.Namespace }}
{{- range $name, $data := .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
      sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  encryptedData:
  {{- toYaml $data | trim | nindent 4 }}
  template:
    metadata:
      name: {{ $name }}
      namespace: {{ $namespace }}
    type: Opaque
status: {}
---
{{- end }}